### ISSUE TITLE
Is the intersection caused by Unity physics engine?

### ISSUE THREAD

**Issue by rampagedog12** [katboi01/UmaViewer#20]
As shown below... I think you may not have time for it, but do you have any ideas to solve this problem...?

![QQ图片20230210214900](https://user-images.githubusercontent.com/25874618/218235178-307519f3-39e6-4831-9f9e-812d40533904.png)
![QQ图片20230210214909](https://user-images.githubusercontent.com/25874618/218235179-376f275c-2a60-4886-8a96-842fa246bcab.png)

**Comment by croakfang** [comment]
The game uses CySpring to calculate skirt collision, which is difficult to implement in the project at present

**Comment by rampagedog12** [comment]
> The game uses CySpring to calculate skirt collision, which is difficult to implement in the project at present

Anywhere we can see the CySpring? Do they publish some scholar paper or you see it when you reverse engineer the game?

**Comment by croakfang** [comment]
I found the code when I reverse the game.
CySpring use a separate controller to calculate the collision between thigh and skirt, I can't figure out the logic of this controller yet
