### ISSUE TITLE
3D model is not displayed after loading character

### ISSUE THREAD

**Issue by zxwwxz001** [katboi01/UmaViewer#35]
the 3D model was not displayed after starting UmaViewer and load the character. 
The display was normal on 10/22. Is it because of the game update?

![image](https://github.com/katboi01/UmaViewer/assets/51045366/885aa56b-04a9-4a80-890a-08c4297b164d)

**Comment by croakfang** [comment]
Yes, the new version of the game utilizes a new rendering method Universal Render Pipeline. The resources from the older version will no longer be compatible. I am currently working on resolving this issue.

**Comment by katboi01** [comment]
Changes were merged, should be good to go.
