### ISSUE TITLE
Excuse me,how long will it take for this project to be updated to adapt to the current version of Pretty Derby?

### ISSUE THREAD

**Issue by TeioDH** [katboi01/UmaViewer#36]
Some time ago, I saw some videos that used the project you developed. I was very interested in it. But when I used it, I found that this version can no longer view the model. I feel very sad about this. I look forward to you updating this project. If possible, please tell me the approximate update time. Thank you and your team.

**Comment by croakfang** [comment]
Yes, the new version of the game utilizes a new rendering method Universal Render Pipeline. The resources from the older version will no longer be compatible. I am currently working on resolving this issue. (check [https://github.com/croakfang/UmaViewer)](https://github.com/croakfang/UmaViewer))

Now that some bugs have been fixed, I will merge the fix into this branch once it is completed

**Comment by GHTGXL** [comment]
> Yes, the new version of the game utilizes a new rendering method Universal Render Pipeline. The resources from the older version will no longer be compatible. I am currently working on resolving this issue. (check [https://github.com/croakfang/UmaViewer)](https://github.com/croakfang/UmaViewer))
> 
> Now that some bugs have been fixed, I will merge the fix into this branch once it is completed

So When I use your umaviewer, the body part is missing, is it because of this?

Like I using 20230911 is fine, but 20231030 and 20231104 has body part missing.

**Comment by katboi01** [comment]
The viewer was synced with CroakFang's changes, you can check it now.
