### ISSUE TITLE
Request for Assistance with Umaviewer and Umachat Issues After Game Update

### ISSUE THREAD

**Issue by chenfeirui** [katboi01/UmaViewer#38]
I apologize for the inconvenience, but after updating my game to the new version, I have encountered issues with both umaviewer and umachat. This has been quite frustrating for me as I have limited knowledge of programming and am unable to resolve the problem of the model not loading. I'm unsure if umachat is also developed by your team, but I sincerely hope that both umaviewer and umachat's issues can be addressed simultaneously. I would like to continue using both umaviewer and umachat. Thank you for your assistance.

**Comment by katboi01** [comment]
Fixed by CroakFang!

Unfortunately I'm not in contact with Kagari so I don't know if the changes will be applied to UmaChat.
