### ISSUE TITLE
About the future.

### ISSUE THREAD

**Issue by Guda-nemo** [katboi01/UmaViewer#4]
Will expressions and motion recording be added in the future? I saw that you did them well on FGO viewer. Is that the limit of API?

**Comment by katboi01** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/59540382/198892694-288d3fc5-5870-4bbd-989b-cdba15afd1e7.gif)
It isn't perfect, but I got it to work. I will add it in an update soon.

**Comment by Guda-nemo** [comment]
Many thanks. Your work is really great. Oh by the way, can you add a function that allows users to customize the background images?

**Comment by katboi01** [comment]
The gif feature is now available in the newest release ^^
As for the backgrounds, there are a lot of variables that come into play... Whether it should follow the camera or not, whether the image fits inside the screen or is cropped, zooming in, moving, rotating the image... I think for all use cases, it's easier and more precise to use an image editor to combine a screenshot with the background. So I think I won't be adding that, unless you can give me a good example of a situation where it's better to do it in the Viewer.

**Comment by Guda-nemo** [comment]
Oh, I guess you're right, background is easy to set by myself. Let me try the new release.
