### ISSUE TITLE
Output PMX files cannot be used in MMD.

### ISSUE THREAD

**Issue by Nijinosaki** [katboi01/UmaViewer#42]
I used UmaViewer_2acf15cb43f3f55d6d0a23b9c81bc82116146ca4, selected the character and clothes, and used [ExportModel] to output a pmx file.
I loaded the output pmx file into MMD, but it only showed [Position] on the bones.
I loaded the live VMD file output by [Record VMD(Slow)] in [Shows(WIP)], but it did not work.
![pmx](https://github.com/katboi01/UmaViewer/assets/78363731/afe695f2-25b3-407e-8de7-9cb445ca6e7a)

**Comment by croakfang** [comment]
The exported PMX model does not have a standard PMX skeleton and needs to be manually processed. But the exported VMD file drives the standard PMX skeleton, which can be directly used on other MMD models.
