### ISSUE TITLE
Excuse me, I want the output GIF to have the same name as the animation clip. What should I do?

### ISSUE THREAD

**Issue by UCHIHAHA103** [katboi01/UmaViewer#43]
just like this
![image](https://github.com/katboi01/UmaViewer/assets/61904674/11e0693d-6572-43a3-8d4d-0bf1e0107019)
I am a programming novice and have tried many methods but have been unable to achieve it. Your answer would be a great help to me！

**Comment by croakfang** [comment]
replace `DateTime.Now.ToString(“yyyy-MM-dd_HH _mm_ss_fff”) `to `UmaViewerBuilder.Instance.CurrentUMAContainer.OverrideController["clip_2"].name`

**Comment by UCHIHAHA103** [comment]
> replace `DateTime.Now.ToString(“yyyy-MM-dd_HH _mm_ss_fff”) `to `UmaViewerBuilder.Instance.CurrentUMAContainer.OverrideController["clip_2"].name`

Thank you for your response, it has resolved a major issue for me!
