### ISSUE TITLE
How to fix camera motion from lives?

### ISSUE THREAD

**Issue by chiakianyka** [katboi01/UmaViewer#44]
Hi! I export camera from live and it not work on MMD
It's turn to be like this anyone know how to fix?

![Screenshot 2023-11-16 231948](https://github.com/katboi01/UmaViewer/assets/71890761/dd331c5f-3b45-49d7-a0d4-6730c866841e)

**Comment by croakfang** [comment]
Load the POS file into an empty model, load the FOV into the camera, and then attach the camera to the model with the loaded POS.
