### ISSUE TITLE
Database not found even DMM umamusume installed and normal loaded 

### ISSUE THREAD

**Issue by 0999312** [katboi01/UmaViewer#45]
After 12.11's update, Database not found even DMM umamusume installed and normal loaded.
Workmode:default and standalone(see below)
Overwriting the master.mdb file provided by standalone workmode with the original master.mdb file will also cause the problem.
See screenshot for details:
![20231211104748](https://github.com/katboi01/UmaViewer/assets/5692449/d5352f5e-ee86-4cf0-bc89-aac27141956a)

**Comment by KawagishiCheval** [comment]
Same.

**Comment by AgnesDigitalIO** [comment]
Yes, after the update on December 12, 2023, the game files areYes, after the update on December 12, 2023, the game files are normal, but it prompts to download. Could it be that Cy has made some changes again?

**Comment by jasonjiang8866** [comment]
same here
