### ISSUE TITLE
I encountered a problem here. 

### ISSUE THREAD

**Issue by byykt** [katboi01/UmaViewer#51]
Hello, dear developer. I would like to ask if there are any tutorial manuals or instructions. I encountered a problem here. The VMD file recorded by umaview cannot be used on the model exported by umaview. It will not generate animation keyframes. The software I use includes MMD, Blender, and Unreal.

**Comment by croakfang** [comment]
vmd recorded by the Viewer uses the standard MMD skeleton, but the model is not. Therefore, you need to process the exported model to the MMD standard skeleton
