### ISSUE TITLE
I have a question about Exporting models.

### ISSUE THREAD

**Issue by batwings7** [katboi01/UmaViewer#52]
Hello, developer. I am enjoying this very much thanks to you. Thank you very, very much. Then, I have a question. I want to export the models using something like Blender. But I saw that you wrote that this option is incomplete. So, I want to know when it will be completed. Well if so, I will be happily waiting for it to be 100 percent. Thanks for developing this awesome, have a nice day.

**Comment by croakfang** [comment]
I plan to complete the export of regular characters, mini characters, and scenes. The first one has already been completed, and the rest will be completed later. Sorry, there is no specific time for this.
