### ISSUE TITLE
Database not found after the update on March 4th.

### ISSUE THREAD

**Issue by konoSanCai** [katboi01/UmaViewer#59]
After downloading all the resources. UmaViewer doesn't work. May there are something new disturbed the program.

**Comment by cao3082423114** [comment]
I thought I was the only one.

**Comment by HosinoPro** [comment]
![スクリーンショット 2024-03-05 190910](https://github.com/katboi01/UmaViewer/assets/50156928/55ef1185-04ab-4f3c-b808-11bbc622f7b9)
Works fine for me.

**Comment by konoSanCai** [comment]
> ![スクリーンショット 2024-03-05 190910](https://private-user-images.githubusercontent.com/50156928/310072055-55ef1185-04ab-4f3c-b808-11bbc622f7b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcyMzQsIm5iZiI6MTcwOTYzNjkzNCwicGF0aCI6Ii81MDE1NjkyOC8zMTAwNzIwNTUtNTVlZjExODUtMDRhYi00ZjNjLWI4MDgtMTFiYmM2MjJmN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTY3MTQwMzhhM2ZlZjFlNmI0MTgwZGIzZWJhY2ZlOWExMTI4OGMzZTJlYWNlZDVmMmRmZWYxNzdjMDc3MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhvbDOMyGKS2OxPYt_SBheWoYl2_essyZkEN8OZek8A) Works fine for me.

Has your umamusume been updated? Before the update it worked fine for me as well. -^-

**Comment by cao3082423114** [comment]
> > ![スクリーンショット 2024-03-05 190910](https://private-user-images.githubusercontent.com/50156928/310072055-55ef1185-04ab-4f3c-b808-11bbc622f7b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcyMzQsIm5iZiI6MTcwOTYzNjkzNCwicGF0aCI6Ii81MDE1NjkyOC8zMTAwNzIwNTUtNTVlZjExODUtMDRhYi00ZjNjLWI4MDgtMTFiYmM2MjJmN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTY3MTQwMzhhM2ZlZjFlNmI0MTgwZGIzZWJhY2ZlOWExMTI4OGMzZTJlYWNlZDVmMmRmZWYxNzdjMDc3MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhvbDOMyGKS2OxPYt_SBheWoYl2_essyZkEN8OZek8A) Works fine for me.
> 
> Has your umamusume been updated? Before the update it worked fine for me as well. -^-

I also can't run after updating

**Comment by konoSanCai** [comment]
Fixed. Thanks to all the contributors.
