### ISSUE TITLE
Excuse me，where can I download the complete game assets? 

### ISSUE THREAD

**Issue by UCHIHAHA103** [katboi01/UmaViewer#60]
I have updated the client to the latest version ,but some game resources seem to require entering certain processes in the game before they can be downloaded. Where can I download the complete game resources?
It seems that this link cannot be opened.
https://prd-storage-umamusume.akamaized.net/dl/resources/
![image](https://github.com/katboi01/UmaViewer/assets/61904674/55a4d6aa-f08d-4217-8d73-2b8cb1c77d2a)
![image](https://github.com/katboi01/UmaViewer/assets/61904674/f46f4e0f-ea64-4891-8add-a088b5c840f9)
![image](https://github.com/katboi01/UmaViewer/assets/61904674/92115291-4cd3-475a-8e29-27871f92474f)

**Comment by UCHIHAHA103** [comment]
Where can I download the complete assets? It seems that this link cannot be opened.
https://prd-storage-umamusume.akamaized.net/dl/resources/

**Comment by croakfang** [comment]
There is an option to download all resources in the game settings.
