### ISSUE TITLE
Animaition Record vmd is weird

### ISSUE THREAD

**Issue by julius128** [katboi01/UmaViewer#61]
i record animations for mmd,but the animations is weird.
but i record characters default animation is fine

**Comment by julius128** [comment]
the leg is fine, but the hand is weird

**Comment by croakfang** [comment]
any pictures or videos?

**Comment by julius128** [comment]
> any pictures or videos?

![Uploading Animation.gif…]()

**Comment by borntree** [comment]
umamusuma models is T-POSE, but most models are A-pose
