### ISSUE TITLE
mini character with anima

### ISSUE THREAD

**Issue by borntree** [katboi01/UmaViewer#65]

**Comment by borntree** [comment]
I export mini character with animations, the .pmx file import blender 3.6 but it has no animations, just T-pose
May I ask if this feature has not been developed yet? Or is there a problem with my operation
![image](https://github.com/katboi01/UmaViewer/assets/82987943/74705972-a8f2-4e89-8e90-6d211f6eb90e)

![image](https://github.com/katboi01/UmaViewer/assets/82987943/9c0f3ae2-1ff4-4ec2-852d-37f1f9287434)

**Comment by croakfang** [comment]
Yep, exporting mini animations is currently not supported.
