### ISSUE TITLE
Downloading Data issue

### ISSUE THREAD

**Issue by 12ThTeaSakura** [katboi01/UmaViewer#76]
The download maybe or may not get stuck.
![QD_4M}ZVJ0MFJ} I~55}KWR](https://github.com/user-attachments/assets/ea547439-d81c-4d84-8af5-f7c11cd68568)
Such as the picture,or ↓
![L$0 ENN) W$27SHD66I0PXM](https://github.com/user-attachments/assets/883ecbfb-0ee2-4d09-920c-3031c8b3bebf)
Sometimes,use VPN can solve this problem,but that's uncertain,It will also get stuck

**Comment by pooki812** [comment]
I'm having the exact same problem with this

I'm just waiting for competent technicians to fix it. 🥲

**Comment by mcmh-master** [comment]
Exactly the same problem as mine..

**Comment by katboi01** [comment]
Fixed in 7f71b16, EN tranlation was removed from the API that was used. From now we'll be using translations from [Hachimi](https://github.com/Hachimi-Hachimi/tl-en)
