### ISSUE TITLE
An Enchantment

### ISSUE THREAD

**Issue by Guda-nemo** [katboi01/UmaViewer#8]
This is just an advice that can you add a function that can make umamusumes' eyes focus on the camera. This will be easier to set more expressions.

**Comment by katboi01** [comment]
The feature is done, only needs to be merged now 👍

**Comment by Guda-nemo** [comment]
I've noticed your pull requests, that's great!!! By the way, can you explain the function of live and live sounds for me? They doesn't work on my conputer so I want to know how they shold work.

**Comment by katboi01** [comment]
I haven't worked on it, but I'm fairly sure [Live] tab only loads the scenery for viewing, not the entire "show". As for [live sounds], once you select a song and vocalist it should start playing the audio. Lyrics for the song should also appear on screen. In the settings tab there is a "Sound" category, there you can pause/rewind the song and/or hide the lyrics.
